/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicine_bs;

import config.connectDB;
import java.sql.ResultSet;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author markjay
 */
public class Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        //remove border
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        loadContent();
    }
    
    public void loadContent() {
        connectDB db = new connectDB();
        
        String userSQL = "SELECT COUNT(*) AS total_users FROM users";
        String orderSQL = "SELECT COUNT(*) AS total_orders FROM order_items";
        String medicineSQL = "SELECT COUNT(*) AS total_medicines FROM medicines";
        
        try(ResultSet rs = db.getData(userSQL)) {
            if(rs.next()) {
                totalUsersLabel.setText(String.valueOf(rs.getInt("total_users")));
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        try(ResultSet rs = db.getData(orderSQL)) {
            if(rs.next()) {
                totalOrdersLabel.setText(String.valueOf(rs.getInt("total_orders")));
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        try(ResultSet rs = db.getData(medicineSQL)) {
            if(rs.next()) {
                totalMedicineLabel.setText(String.valueOf(rs.getInt("total_medicines")));
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        totalUsersLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalMedicineLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        totalOrdersLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 640, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalUsersLabel.setBackground(new java.awt.Color(51, 51, 51));
        totalUsersLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        totalUsersLabel.setText("0");
        jPanel2.add(totalUsersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Total Users");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 210, 180));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Total Medicine");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        totalMedicineLabel.setBackground(new java.awt.Color(51, 51, 51));
        totalMedicineLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        totalMedicineLabel.setText("0");
        jPanel3.add(totalMedicineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 210, 180));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Total orders");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        totalOrdersLabel.setBackground(new java.awt.Color(51, 51, 51));
        totalOrdersLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        totalOrdersLabel.setText("0");
        jPanel4.add(totalOrdersLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 220, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel totalMedicineLabel;
    private javax.swing.JLabel totalOrdersLabel;
    private javax.swing.JLabel totalUsersLabel;
    // End of variables declaration//GEN-END:variables
}
