/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicine_bs;

import java.awt.Color;

/**
 *
 * @author mikel
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
    }
    
        private Color hoverColor = new Color(180, 180, 180); // Grayish color on hover
        private Color defaultColor = new Color(255, 255, 255); // Default white color
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Panel = new javax.swing.JPanel();
        Ttile = new javax.swing.JLabel();
        ufeld = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        pfield = new javax.swing.JPasswordField();
        pass = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        exit = new javax.swing.JPanel();
        ex = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        log = new javax.swing.JLabel();
        new_user = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ttile.setFont(new java.awt.Font("Arial Black", 1, 23)); // NOI18N
        Ttile.setForeground(new java.awt.Color(0, 102, 102));
        Ttile.setText("MEDICINE BILLING SYSTEM");
        Login_Panel.add(Ttile, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 410, 60));

        ufeld.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        ufeld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ufeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufeldActionPerformed(evt);
            }
        });
        Login_Panel.add(ufeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, 40));

        user.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(0, 102, 102));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Username");
        Login_Panel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 240, -1));

        pfield.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        pfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfieldActionPerformed(evt);
            }
        });
        Login_Panel.add(pfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 240, 40));

        pass.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        pass.setForeground(new java.awt.Color(0, 102, 102));
        pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pass.setText("Password");
        Login_Panel.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 240, -1));

        role.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        Login_Panel.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 40));

        ex.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        ex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ex.setText("EXIT");

        javax.swing.GroupLayout exitLayout = new javax.swing.GroupLayout(exit);
        exit.setLayout(exitLayout);
        exitLayout.setHorizontalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        exitLayout.setVerticalGroup(
            exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Login_Panel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 90, 30));

        log.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        log.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        log.setText("LOGIN");

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Login_Panel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 90, 30));

        new_user.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        new_user.setForeground(new java.awt.Color(0, 102, 102));
        new_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        new_user.setText("New user? ");
        Login_Panel.add(new_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 80, -1));

        reg.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        reg.setForeground(new java.awt.Color(102, 0, 102));
        reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reg.setText("Click here to register");
        reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regMouseClicked(evt);
            }
        });
        Login_Panel.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image1.png"))); // NOI18N
        Login_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        welcome.setFont(new java.awt.Font("Arial Black", 1, 35)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 102, 102));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("WELCOME!");
        Login_Panel.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 410, 60));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nim1.png"))); // NOI18N
        Login_Panel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfieldActionPerformed

    private void ufeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufeldActionPerformed

    private void regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseClicked
        Registers reg = new Registers();
        reg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_regMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JLabel Ttile;
    private javax.swing.JLabel ex;
    private javax.swing.JPanel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel log;
    private javax.swing.JPanel login;
    private javax.swing.JLabel new_user;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField pfield;
    private javax.swing.JLabel reg;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField ufeld;
    private javax.swing.JLabel user;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
